### ISSUE TITLE
Bookmark/Tab name includes default text

### ISSUE THREAD

**Issue by mindlessha** [tomtheisen/mutraction#1]
When viewing webpage, tab displays website name, then default text "boilerplate-free web apps. 
Mutraction | Boilerplate-free web apps

Is that your tag line??

**Comment by tomtheisen** [comment]
It's one of many.  I could change it.  Maybe something about mutation?

**Comment by tomtheisen** [comment]
I see what you mean.  It didn't come from a template.  I actually typed it.  I'll keep it this way until a better slogan makes itself evident.
