### ISSUE TITLE
Period should go after parenthetical phrase 

### ISSUE THREAD

**Issue by mindlessha** [tomtheisen/mutraction#2]
Under Getting Started - Topics - Model tracking, the first sentence under the subheading "How Does it work?" incorrectly places a period before the parenthetical phrase. The period should be moved to after the end parenthesis.

...on property reads, writes, and deletes. (among other things)

Update to:
...on property reads, writes, and deletes (among other things).

**Comment by tomtheisen** [comment]
Fixed in b8f44e21aed3d5a37f87acd04af910cdc8421a42, but not yet published to the live docs site.  It will be included during the next publish.
