### ISSUE TITLE
Duplicate Word "dependency"

### ISSUE THREAD

**Issue by mindlessha** [tomtheisen/mutraction#7]
the word dependency is listed twice in a row...I think this is a mistake.

In this case, there's one dependency dependency registered for child text node.

remove one instance of dependency.

In Topics - One-way binding, step 3 last sentence.

**Comment by tomtheisen** [comment]
Fixed in 15346145e2b87a75c63543da5472901a73ebd572

**Comment by tomtheisen** [comment]
Thanks for the report
